#pragma once

enum
{	
	CHUNK_ELEMENT_DATA = 0,
	CHUNK_ELEMENT_TASK,
	CHUNK_ELEMENT_POLICY,
	CHUNK_ELEMENT_INTERFACEHINT,
	CHUNK_ELEMENT_INTERFACESTRING,
	CHUNK_ELEMENT_ITEMDESC,
	CHUNK_ELEMENT_ITEMEXDESC,
	CHUNK_ELEMENT_SKILLDESC,
	CHUNK_ELEMENT_FIXMSG,
	CHUNK_ELEMENT_SERVERERR,
	CHUNK_ELEMENT_PRECINCT,
	CHUNK_ELEMENT_HELPSCRIPT,
	CHUNK_ELEMENT_HELPTEXT,
	//CHUNK_ELEMENT_TREASURE,
	//CHUNK_ELEMENT_TRANSTARGET,
	CHUNK_ELEMENT_GSHOP,
	CHUNK_ELEMENT_GSHOP_TYPES,
	CHUNK_ELEMENT_BUFFDESC,
	CHUNK_ELEMENT_TASKERR,
	CHUNK_ELEMENT_TEXTFILE,
	CHUNK_ELEMENT_INSTANCE_TEXT,
	CHUNK_ELEMENT_LOADINGHINT,
	CHUNK_ELEMENT_PETTALK,
	CHUNK_ELEMENT_GSHOP1,
	CHUNK_ELEMENT_GSHOP_TYPES1,
	CHUNK_ELEMENT_ADDONSTR,
	CHUNK_ELEMENT_HOMETOWN,
	CHUNK_ELEMENT_DOMAININFOR,
	CHUNK_ELEMENT_DOMAININFOR1,
	CHUNK_ELEMENT_GSHOP2,
	CHUNK_ELEMENT_GSHOP_TYPES2,
	CHUNK_NUM
};

extern const TCHAR* g_szChunk[CHUNK_NUM];

enum THD_STATE
{
	THD_RUN, THD_FIN, THD_FAIL, THD_ABORT
};

struct THD_INFO
{
	THD_STATE	iThdState;
	bool		bAbort;
	TCHAR		szProgMsg[512];
	int			iPercent;
	bool		bMsgUpdate;
};

// Çå³ýÈßÓàÎÄ¼þ
bool CleanUpPckRedundancy(const char* szFilePath);