//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ElementLocalize.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_ELEMENTLOCALIZE_FORM        101
#define IDR_MAINFRAME                   128
#define IDR_ELEMENTYPE                  129
#define IDD_DIALOG_TREE_VIEW            130
#define IDB_LISTTAG                     131
#define IDD_DIALOG_IMPORT_GAME_DATA     132
#define IDD_DIALOG_SELECT_TRANS_TEXT    133
#define IDI_ICON_NORMAL                 134
#define IDI_ICON_DEL                    135
#define IDI_ICON_NEW                    136
#define IDD_DIALOG_FINDER               138
#define IDD_SELECT_ITEMS                139
#define IDD_DIALOG_TOXML                140
#define IDD_DIALOG_PROG                 141
#define IDC_TREE_DATA                   1000
#define IDC_EDIT1                       1001
#define IDC_EDIT_ORG                    1001
#define IDC_EDIT_TRANS1                 1001
#define IDC_EDIT_TEXT                   1001
#define IDC_EDIT_LABEL                  1001
#define IDC_EDIT2                       1002
#define IDC_EDIT_TRANS                  1002
#define IDC_EDIT_ORGTEXT                1002
#define IDC_BUTTON1                     1003
#define IDC_BUTTON_REPLACE              1003
#define IDC_EDIT_TRANS2                 1003
#define IDC_STATIC_LENGTH               1004
#define IDC_EDIT_ORGTEXT2               1004
#define IDC_STATIC_IS_MULTI_LINE        1005
#define IDC_STATIC_LINE_NUM             1006
#define IDC_STATIC_TEXT_LIMIT           1007
#define IDC_STATIC_TRANS_LINE_NUM       1008
#define IDC_STATIC_TRANS_LENGTH         1009
#define IDC_STATIC_ORG                  1010
#define IDC_STATIC_FLAG                 1011
#define IDC_STATIC_TRANS                1012
#define IDC_PROGRESS                    1013
#define IDC_BUTTON_AUTO_TRANS           1013
#define IDC_RADIO_TWO                   1014
#define IDC_PROGRESS_TOTAL              1014
#define IDC_BUTTON_REPLACE_NEXT         1014
#define IDC_RADIO_ONE                   1015
#define IDC_CHECK_APPLYALL              1016
#define IDC_CHECK_MATCH_WHOLE           1017
#define IDC_RADIO_UP                    1018
#define IDC_RADIO_DOWN                  1019
#define IDC_RADIO_TRANS                 1020
#define IDC_RADIO_ORG                   1021
#define IDC_TEMPLATE                    1021
#define IDC_CHECK_ONLY_NEW_ITEM         1022
#define IDC_INTERFACE_HINT              1022
#define IDC_RADIO_USE_ID                1023
#define IDC_INTERFACE_STRING            1023
#define IDC_TASK                        1024
#define IDC_RADIO_USE_TEMP_ID           1024
#define IDC_POLICY                      1025
#define IDC_ITEM_DESC                   1026
#define IDC_ITEM_DESC_EXT               1027
#define IDC_INSTANCE_TEXT               1028
#define IDC_SKILL_DESC                  1029
#define IDC_FIX_MSG                     1030
#define IDC_SERVER_ERROR                1031
#define IDC_BUFF_DESC                   1032
#define IDC_TASK_ERROR                  1033
#define IDC_LOADING_HINT                1034
#define IDC_PET_TALK                    1035
#define IDC_ADDON_STRING                1036
#define IDC_PRECINCT                    1037
#define IDC_HELP_SCRIPT                 1038
#define IDC_HELP_TEXT                   1039
#define IDC_GSHOP                       1040
#define IDC_GSHOP_TYPES                 1041
#define IDC_GSHOP1                      1042
#define IDC_GSHOP1_TYPES                1043
#define IDC_SELECT_ALL                  1044
#define IDC_SCRIPT                      1045
#define IDC_CK_LABEL                    1046
#define IDC_HOMETOWN                    1047
#define IDC_CHECK_ID                    1048
#define IDC_DOMAIN_INFO                 1048
#define IDC_CHECK_UNTRANS               1049
#define IDC_DOMAIN_INFO2                1049
#define IDC_EDIT_ID                     1050
#define IDC_STATIC_PERCENT              1051
#define IDC_GSHOP2                      1051
#define IDC_STATIC_MSG                  1052
#define IDC_GSHOP2_TYPES                1052
#define IDC_CHECK_ORG                   1053
#define ID_IMPORT_GAME_DATA             32771
#define ID_DATA_OPEN                    32772
#define ID_DATA_SAVE                    32773
#define ID_DATA_SAVE_AS                 32774
#define ID_PREV                         32775
#define ID_NEXT                         32776
#define ID_IMPORT_OTHER                 32777
#define ID_FIND_NEW_ITEM                32778
#define ID_FIND_TEXT                    32784
#define ID_FIND_NEXT                    32786
#define ID_EXPORT_GAME_DATA             32788
#define ID_GO_SEL                       32789
#define ID_FIND_NEW_ITEMEX              32790
#define ID_STAT_ITEMS                   32791
#define ID_HELP_EXT                     32792
#define ID_SAVE_TEXT_TO_FILE            32793
#define ID_IMPORT_FROM_TEXT_FILE        32794
#define ID_CHECK_SYNAC                  32795
#define ID_AUTO_TO_BIG5                 32796
#define ID_FIND_UP                      32797
#define ID_FIND_DOWN                    32798
#define ID_SAVE_OPT                     32799
#define ID_SAVE_CUSTOM                  32800
#define ID_DATA_SAVE_CUSTOM             32801
#define ID_IMPORT_ORDER_TEXT            32802
#define ID_COPY_ORIGIN_TO_TRANS         32803
#define ID_CLEAR_TRANS                  32804
#define ID_INDICATOR_TOTAL              59143
#define ID_INDICATOR_TRANS              59144
#define ID_INDICATOR_DISUSE             59145
#define ID_INDICATOR_NEW                59146

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32805
#define _APS_NEXT_CONTROL_VALUE         1055
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
