#ifndef _SINGLETON_H_
#define _SINGLETON_H_

#include <assert.h>

#if defined(_MSC_VER)
// Turn off warnings generated by this singleton implementation
#   pragma warning (disable : 4311)
#   pragma warning (disable : 4312)
#endif

template <typename T>
class Singleton
{
public:
	Singleton()
	{
		assert(!ms_Singleton);
	#if defined(_MSC_VER) && _MSC_VER < 1200
		int offset	 = (int)(T*)1 - (int)(Singleton<T>*)(T*)1;
		ms_Singleton = (T*)(int(this)+offset); 
	#else
		ms_Singleton = static_cast<T*>(this);
	#endif
	}
	
	~Singleton()
	{
		assert(ms_Singleton);
		ms_Singleton = 0;
	}

protected:
	static T*	ms_Singleton;

public:
	static T&	GetSingleton()
	{
		assert(ms_Singleton);
		return (*ms_Singleton);
	}

	static T*	GetSingletonPtr()
	{
		return ms_Singleton;
	}
};

#endif