/*
 * FILE: EC_MsgDef.h
 *
 * DESCRIPTION: 
 *
 * CREATED BY: Duyuxin, 2004/8/30
 *
 * HISTORY: 
 *
 * Copyright (c) 2004 Archosaur Studio, All Rights Reserved.
 */

#pragma once

///////////////////////////////////////////////////////////////////////////
//	
//	Define and Macro
//	
///////////////////////////////////////////////////////////////////////////

//	Fixed message define
enum
{
	FIXMSG_PICKUPMONEY = 0,		//	0
	FIXMSG_GOTEXP,
	FIXMSG_LOSTEXP,
	FIXMSG_LEVELUP,
	FIXMSG_GOTSP,

	FIXMSG_PICKUPITEM,			//	5
	FIXMSG_LEAVETEAM,
	FIXMSG_KICKEDOUTTEAM,
	FIXMSG_CANCELTEAM,
	FIXMSG_JOINTEAM,
	
	FIXMSG_REJECTJOINTEAM,		//	10
	FIXMSG_TEAMMEMPICKUP,
	FIXMSG_CHAT,
	FIXMSG_PRIVATECHAT1,
	FIXMSG_PRIVATECHAT2,

	FIXMSG_GAINITEM,			//	15
	FIXMSG_PRODUCEITEM,
	FIXMSG_MISSED,
	FIXMSG_DISCONNECTED,
	FIXMSG_NOTARGET,

	FIXMSG_TARGETISFAR,			//	20
	FIXMSG_TEAMMEMKICKEDOUT,
	FIXMSG_WRONGVERSION,
	FIXMSG_OFFLINE,
	FIXMSG_DODAMAGE,

	FIXMSG_BEDAMAGED,			//	25
	FIXMSG_INVALIDWEAPON,
	FIXMSG_TARGETWRONG,
	FIXMSG_WRONGCUSTOMDATA,
	FIXMSG_SEARCHTEAM,

	FIXMSG_SEARCHTEAMMEM,		//	30
	FIXMSG_LEVELANDPROF,
	TODEL_FIXMSG_PROFOLD1_1,
	TODEL_FIXMSG_PROFOLD1_2,
	TODEL_FIXMSG_PROFOLD1_3,

	TODEL_FIXMSG_PROFOLD1_4,		//	35
	TODEL_FIXMSG_PROFOLD1_5,
	TODEL_FIXMSG_PROFOLD1_6,
	TODEL_FIXMSG_PROFOLD1_7,
	TODEL_FIXMSG_PROFOLD1_8,
	
	FIXMSG_PACKFULL1,			//	40
	FIXMSG_PACKFULL2,
	FIXMSG_NOTTRADEITEM,
	FIXMSG_NEEDTOOL,
	FIXMSG_GOTREP,
	
	FIXMSG_LEVEL2_01,
	FIXMSG_LEVEL2_02,
	FIXMSG_LEVEL2_03,
	FIXMSG_LEVEL2_04,
	FIXMSG_LEVEL2_05,

	FIXMSG_LEVEL2_06,			//	50
	FIXMSG_LEVEL2_07,
	FIXMSG_LEVEL2_08,
	FIXMSG_LEVEL2_09,
	FIXMSG_LEVEL2_20,

	FIXMSG_LEVEL2_21,
	FIXMSG_LEVEL2_22,
	FIXMSG_LEVEL2_30,
	FIXMSG_LEVEL2_31,
	FIXMSG_LEVEL2_32,

	FIXMSG_LEVEL2UP,			//	60
	FIXMSG_PACKISFULL,
	FIXMSG_FAILEDTOCONN,
	FIXMSG_ENTERSHELTER,
	FIXMSG_LEAVESHELTER,
	
	FIXMSG_KICKOUTROLE,
	FIXMSG_KICKOUTUSER,
	FIXMSG_ONLINENUMBER,
	FIXMSG_RESTARTSEV,
	FIXMSG_SHUTUPROLE,
	
	FIXMSG_SHUTUPUSER,			//	70
	FIXMSG_NEEDMONEY,
	FIXMSG_SCREENSHOT,
	FIXMSG_NEEDMP,
	FIXMSG_MYFRIEND,

	FIXMSG_MSGSENDFAIL,
	FIXMSG_MSGSENDWAIT,
	FIXMSG_OPTSUCCESS,
	FIXMSG_OFFLINE2,
	FIXMSG_OPTOVERTIME,

	FIXMSG_REFUSEFRIEND,		//	80
	FIXMSG_GENDER_MALE,
	FIXMSG_GENDER_FEMALE,
	FIXMSG_NEWWAYPOINT,
	FIXMSG_BOOTHSELL,

	FIXMSG_BOOTHBUY,			//	85
	FIXMSG_FRIEND_OT,			//	Add friend overtime
	FIXMSG_SERVERCLOSE,
	FIXMSG_WRONGROLE,
	FIXMSG_SKILLINTERRUPT,
	
	FIXMSG_LOSEITEM,			//	90
	FIXMSG_ITEMDISAPPEAR,
	FIXMSG_ERR_FC_NETWORKERR,
	FIXMSG_ERR_FC_INVALID_OPERATION,
    FIXMSG_ERR_FC_OP_TIMEOUT,

    FIXMSG_ERR_FC_CREATE_ALREADY,	//	95
    FIXMSG_ERR_FC_CREATE_DUP,
    FIXMSG_ERR_FC_DBFAILURE,
    FIXMSG_ERR_FC_NO_PRIVILEGE,
    FIXMSG_ERR_FC_INVALIDNAME,

    FIXMSG_ERR_FC_FULL,				//	100
    FIXMSG_ERR_FC_APPLY_REJOIN,
    FIXMSG_ERR_FC_JOIN_SUCCESS,
    FIXMSG_ERR_FC_JOIN_REFUSE,
    FIXMSG_ERR_FC_ACCEPT_REACCEPT,

    FIXMSG_ERR_FC_FACTION_NOTEXIST,	//	105
    FIXMSG_ERR_FC_NOTAMEMBER,
    FIXMSG_ERR_FC_CHECKCONDITION,
    FIXMSG_ERR_FC_DATAERROR,
	FIXMSG_FC_CREATE,

	FIXMSG_FC_ACCEPT_JOIN,			//	110
	FIXMSG_FC_EXPEL,
	FIXMSG_FC_RESIGN,
	FIXMSG_FC_APPOINT,
	FIXMSG_FC_LEAVE,

	FIXMSG_FC_DISMISS,				//	115
	FIXMSG_FC_RENAME,
	FIXMSG_FC_CHG_PROCLAIM,
	FIXMSG_ERR_INSTDATA,
	FIXMSG_NEEDAP,
	
	FIXMSG_ITEM_CANNOTUSE,			//	120
	FIXMSG_ITEM_INCOOLTIME,
	FIXMSG_CMD_INCOOLTIME,
	FIXMSG_ADDMAXAP,
	FIXMSG_TRASHBOX_EXPAND,

	FIXMSG_FC_UPGRADE,				//	125
	FIXMSG_FC_DEGRADE,
	FIXMSG_ERR_FC_OFFLINE,
	FIXMSG_SKILL_INVALIDSTATE,
	FIXMSG_BEKILLED,
	
	FIXMSG_NOTENOUGHAMMO,			//	130
	FIXMSG_LEVELTOOLOW,
	FIXMSG_CHAT2,
	FIXMSG_FORBIDTIME,
	FIXMSG_FORBIDLOGIN,

	FIXMSG_FORBIDTALK,				//	135
	FIXMSG_FORBIDTRADE,
	FIXMSG_FORBIDSELL,
	FIXMSG_FORBIDREASON,
	FIXMSG_DUEL_WIN,

	FIXMSG_DUEL_DRAW,				//	140
	FIXMSG_DUEL_INFIGHT,
	FIXMSG_DUEL_ASKSENT,
	FIXMSG_WRONGPROF,
	FIXMSG_PET_HATCH,

	FIXMSG_PET_FREE,				//	145
	FIXMSG_PET_CORRALFULL,
	FIXMSG_FCRANK_MASTER,
	FIXMSG_FCRANK_VICEMASTER,
	FIXMSG_FCRANK_BODYGUARD,

	FIXMSG_FCRANK_POINEER,			//	150
	FIXMSG_FCRANK_MEMBER,
	FIXMSG_SERVERUPDATE,
	FIXMSG_BAT_INVADER_WIN,
	FIXMSG_BAT_DEFENDER_WIN,
	
	FIXMSG_OBTAINTANK,				//	155
	FIXMSG_LOSETANK,
	FIXMSG_PET_DEAD,
	FIXMSG_GM_INVISIBLE,
	FIXMSG_GM_VISIBLE,

	FIXMSG_GM_INVINCIBLE,			//	160
	FIXMSG_GM_VINCIBLE,
	FIXMSG_PROFOLD_1,
	FIXMSG_PROFOLD_2,
	FIXMSG_PROFOLD_3,

	FIXMSG_PROFOLD_4,				//	165
	FIXMSG_PROFOLD_5,
	FIXMSG_PROFOLD_6,
	FIXMSG_PROFOLD_7,
	FIXMSG_PROFOLD_8,

	FIXMSG_PROFOLD_9,				//	170
	FIXMSG_PROFOLD_10,
	FIXMSG_PROFOLD_11,
	FIXMSG_PROFOLD_12,
	FIXMSG_PROFOLD_13,

	FIXMSG_PROFOLD_14,				//	175
	FIXMSG_PROFOLD_15,
	FIXMSG_ERR_GSHOPDATA,
	FIXMSG_NEW_INVENTORY_SIZE,
	FIXMSG_ITEMEXPIRED,

	FIXMSG_PROD_LEVELUP,			//	180
	FIXMSG_AUTOSELECT_FAIL,
	FIXMSG_ITEMBIND,
	FIXMSG_BINDAFTEREQUIP,
	FIXMSG_GOTREPUTATION,

	FIXMSG_LOSTREPUTATION,			//	185
	FIXMSG_GOTREGIONREPU,
	FIXMSG_LEARNSKILL,
	FIXMSG_FRIENDLISTFULL,
	FIXMSG_GOTMARRIED,			

	FIXMSG_GOTDIVORCED,				// 190
	FIXMSG_GOTTITLE,		
	FIXMSG_RECORD_START,
	FIXMSG_RECORD_END,
	FIXMSG_AUTOMOVE_SEARCHING,

	FIXMSG_AUTOMOVE_INVALID_POS,	// 195   //invalid end pos
	FIXMSG_FACTION_TRASHBOX_EXPAND,
	FIXMSG_AUTOMOVE_NO_PATH,
	FIXMSG_SECT_1,
	FIXMSG_SECT_2,

	FIXMSG_SECT_3,					// 200
	FIXMSG_SECT_4,
	FIXMSG_SECT_5,
	FIXMSG_SECT_6,
	FIXMSG_SECT_7,
					
	FIXMSG_SECT_8,					// 205
	FIXMSG_SECT_9,
	FIXMSG_SECT_10,
	FIXMSG_SECT_11,
	FIXMSG_SECT_12,

	FIXMSG_SECT_13,					// 210
	FIXMSG_SECT_14,
	FIXMSG_SECT_15,
	FIXMSG_SECT_16,
	FIXMSG_SECT_17,
	FIXMSG_SECT_18,

	FIXMSG_LEVEL2_1,				// 215
	FIXMSG_LEVEL2_2,
	FIXMSG_LEVEL2_3,
	FIXMSG_LEVEL2_4,

	FIXMSG_LEVEL2_5,				// 220
	FIXMSG_LEVEL2_6,
	FIXMSG_LEVEL2_7,
	FIXMSG_LEVEL2_8,
	FIXMSG_FC_ACCEPT_JOIN2,

	FIXMSG_GOT_SECT_REPU,			// 225
	FIXMSG_GOT_LOYALTY,
	FIXMSG_FAMILY_CREATE,
	FIXMSG_FAMILY_ACCEPT,
	FIXMSG_FAMILY_EXPEL,

	FIXMSG_FAMILY_APPOINT,			// 230
	FIXMSG_FAMILY_LEAVE,
	FIXMSG_FAMILY_CHANGE_PROCLAIM,
	FIXMSG_FAMILY_DISMISS,
	FIXMSG_FAMILY_ACCEPT_SELF,

	FIXMSG_FAMILY_EXPEL_SELF,		// 235
	FIXMSG_FAMILY_LEAVE_SELF,
	FIXMSG_FC_ACCEPT_SELF,
	FIXMSG_FC_EXPEL_SELF,
	FIXMSG_FC_LEAVE_SELF,

	FIXMSG_FC_APPOINT_MASTER,		// 240
	FIXMSG_ERR_FC_INVITEELEVEL,
	FIXMSG_FC_DISMISS_CANCEL,
	FIXMSG_FC_DISMISS_OPRT,
	FIXMSG_COOLING,

	FIXMSG_ERR_FC_DISMISSWAITING,	// 245
	FIXMSG_ERR_FC_INVITEENOFAMILY,
	FIXMSG_AUTOMOVE_INVALID_MAP,
	FIXMSG_AUTOMOVE_INVALID_START,
	FIXMSG_AUTOMOVE_FORBID,

	FIXMSG_AUTOMOVE_BEGIN,			//250
	FIXMSG_AUTOMOVE_END,
	FIXMSG_AUTOMOVE_CANCEL,  
	FIXMSG_FAMILY_DISMISS_CANCEL,
	FIXMSG_FAMILY_DISMISS_OPRT,

	FIXMSG_ERR_FC_LEAVINGFAMILY,	// 255
	FIXMSG_GOT_QINGYUAN,
	FIXMSG_GOT_WENCAI,	
	FIXMSG_LEARNTALENT,
	FIXMSG_PROFOLD1_1,

	FIXMSG_PROFOLD1_2,					// 260
	FIXMSG_PROFOLD1_3,
	FIXMSG_PROFOLD1_4,				
	FIXMSG_PROFOLD1_5,
	FIXMSG_PROFOLD1_6,

	FIXMSG_PROFOLD1_7,					// 265
	FIXMSG_PROFOLD1_8,
	FIXMSG_PROFOLD1_9,			
	FIXMSG_PROFOLD1_10,
	FIXMSG_PROFOLD1_11,

	FIXMSG_PROFOLD1_12,					// 270
	FIXMSG_PROFOLD1_13,
	FIXMSG_PROFOLD1_14,
	FIXMSG_PROFOLD1_15,
	FIXMSG_PROFOLD1_16,

	FIXMSG_PROFOLD1_17,					// 275
	FIXMSG_PROFOLD1_18,
	FIXMSG_PROFOLD1_19,
	FIXMSG_PROFOLD1_20,
	FIXMSG_PROFOLD1_21,

	FIXMSG_PROFOLD1_22,					// 280
	FIXMSG_PROFOLD1_23,
	FIXMSG_PROFOLD1_24,
	FIXMSG_PROFOLD1_25,
	FIXMSG_BATTLESCORE_INC,

	FIXMSG_BATTLESCORE_DEC,				// 285
	FIXMSG_CITYOWNER_MASTER,
	FIXMSG_CITYOWNER_VICEMASTER,
	FIXMSG_CITYOWNER_BODYGUARD,
	FIXMSG_CITYOWNER_HEADER,

	FIXMSG_CITYOWNER_MEMBER,			// 290
	FIXMSG_PET_RACE1,
	FIXMSG_PET_RACE2,
	FIXMSG_PET_RACE3,
	FIXMSG_PET_RACE4,

	FIXMSG_PET_RACE5,					// 295
	FIXMSG_PET_RACE6,
	FIXMSG_PET_RACE7,
	FIXMSG_PET_RACE8,
	FIXMSG_PET_RACE9,

	FIXMSG_PET_RACE10,					// 300
	FIXMSG_PET_RACE11,
	FIXMSG_PET_RACE12,
	FIXMSG_PET_RACE13,
	FIXMSG_PET_RACE14,

	FIXMSG_PET_RACE15,					// 305
	FIXMSG_PET_RACE16,
	FIXMSG_PET_ASTRO1,
	FIXMSG_PET_ASTRO2,
	FIXMSG_PET_ASTRO3,

	FIXMSG_PET_ASTRO4,					// 310
	FIXMSG_PET_ASTRO5,
	FIXMSG_PET_ASTRO6,
	FIXMSG_PET_ASTRO7,
	FIXMSG_PET_ASTRO8,

	FIXMSG_PET_ASTRO9,					// 315
	FIXMSG_PET_LOC1,
	FIXMSG_PET_LOC2,
	FIXMSG_PET_LOC3,
	FIXMSG_PET_LOC4,

	FIXMSG_PET_LOC5,					// 320
	FIXMSG_PET_LOC6,
	FIXMSG_PET_LOC7,
	FIXMSG_PET_LOC8,
	FIXMSG_PET_LOC9,

	FIXMSG_PET_LOC10,					// 325
	FIXMSG_PET_LOC11,
	FIXMSG_PET_LOC12,
	FIXMSG_WHOSETHING,
	FIXMSG_PROF_1,

	FIXMSG_PROF_2,						// 330
	FIXMSG_PROF_3,
	FIXMSG_PROF_4,				
	FIXMSG_PROF_5,
	FIXMSG_PROF_6,

	FIXMSG_PROF_7,						// 335
	FIXMSG_PROF_8,
	FIXMSG_PROF_9,			
	FIXMSG_PROF_10,
	FIXMSG_PROF_11,

	FIXMSG_PROF_12,						// 340
	FIXMSG_PROF_13,
	FIXMSG_PROF_14,
	FIXMSG_PROF_15,
	FIXMSG_PROF_16,

	FIXMSG_PROF_17,						// 345
	FIXMSG_PROF_18,
	FIXMSG_PROF_19,
	FIXMSG_PROF_20,
	FIXMSG_PROF_21,

	FIXMSG_PROF_22,						// 350
	FIXMSG_PROF_23,
	FIXMSG_PROF_24,
	FIXMSG_PROF_25,
	FIXMSG_PROF_26,

	FIXMSG_PROF_27,						// 355
	FIXMSG_PROF_28,
	FIXMSG_PROF_29,
	FIXMSG_PROF_30,
	FIXMSG_PROF_31,

	FIXMSG_PROF_32,						// 360
	FIXMSG_PROF_33,
	FIXMSG_PROF_34,
	FIXMSG_PROF_35,
	FIXMSG_PROF_36,

	FIXMSG_PROF_37,						// 365
	FIXMSG_PROF_38,
	FIXMSG_PROF_39,
	FIXMSG_PROF_40,
	FIXMSG_PROF_41,

	FIXMSG_PROF_42,						// 370
	FIXMSG_PROF_43,
	FIXMSG_PROF_44,
	FIXMSG_PROF_45,
	FIXMSG_PROF_46,

	FIXMSG_PROF_47,						// 375
	FIXMSG_PROF_48,
	FIXMSG_PROF_49,
	FIXMSG_PROF_50,
	FIXMSG_PROF_51,

	FIXMSG_PROF_52,						// 380
	FIXMSG_PROF_53,
	FIXMSG_PROF_54,
	FIXMSG_PROF_55,
	FIXMSG_PROF_56,

	FIXMSG_PROF_57,						// 385
	FIXMSG_PROF_58,
	FIXMSG_PROF_59,
	FIXMSG_PROF_60,
	FIXMSG_PROF_61,

	FIXMSG_PROF_62,						// 390
	FIXMSG_PROF_63,
	FIXMSG_PROF_64,
	FIXMSG_PROF_REV,
	FIXMSG_PROF_REV2,

	FIXMSG_GOD_DEVIL_1,					// 395
	FIXMSG_GOD_DEVIL_2,
	FIXMSG_GOD_DEVIL_3,
	FIXMSG_GOD_DEVIL_4,
	FIXMSG_GOD_DEVIL_5,

	FIXMSG_GOD_DEVIL_6,					// 400
	FIXMSG_GOT_REGION_REPU,
	FIXMSG_REGION_REPU_1,
	FIXMSG_REGION_REPU_2,
	FIXMSG_REGION_REPU_3,

	FIXMSG_REGION_REPU_4,				// 405
	FIXMSG_REGION_REPU_5,
	FIXMSG_REGION_REPU_6,
	FIXMSG_REGION_REPU_7,
	FIXMSG_REGION_REPU_8,

	FIXMSG_REGION_REPU_9,				// 410
	FIXMSG_REGION_REPU_10,
	FIXMSG_REGION_REPU_11,
	FIXMSG_REGION_REPU_12,
	FIXMSG_REGION_REPU_13,

	FIXMSG_REGION_REPU_14,				// 415
	FIXMSG_REGION_REPU_15,
	FIXMSG_REGION_REPU_16,
	FIXMSG_REGION_REPU_17,
	FIXMSG_REGION_REPU_18,

	FIXMSG_REGION_REPU_19,				// 420
	FIXMSG_REGION_REPU_20,
	FIXMSG_REGION_REPU_21,
	FIXMSG_REGION_REPU_22,
	FIXMSG_REGION_REPU_23,

	FIXMSG_REGION_REPU_24,				// 425
	FIXMSG_LOST_REGION_REPU,
	FIXMSG_SKILL_COST_ITEM,
	FIXMSG_BOSSKEY_REG_BY_OTHER,
	FIXMSG_GIFT_BAG_GENDER_LIMIT,		// 性别不满足

	FIXMSG_GIFT_BAG_REBORN_LIMIT,		// 430 重生次数不满足
	FIXMSG_GIFT_BAG_PREF_LIMIT,			// 职业不满足	
	FIXMSG_GIFT_BAG_CULTI_LIMIT,		// 造化值不满足
	FIXMSG_GIFT_BAG_LACK_ITEM,			// 缺少打开礼包的道具
	FIXMSG_GIFT_BAG_LACK_MONEY,			// 缺少打开礼包的金钱不足

	FIXMSG_GIFT_BAG_LACK_SPACE,			// 435 包裹缺少足够的空间
	FIXMSG_NAME_COMBINE,				// 名字组合"%s的%s"
	FIXMSG_LEVELTOOHIGH,				// 您的等级大于打开礼包的等级上限
	FIXMSG_ALREADY_VIPSTATE,			// 已经处于VIP状态
	FIXMSG_HP_COOLTIME,					// 瞬回hp冷却
	
	FIXMSG_MP_COOLTIME,					// 440 瞬回mp冷却
	FIXMSG_HPMP_COOLTIME,				// 瞬回hp和mp冷却
	FIXMSG_SLOW_HP_COOLTIME,			// 持续回hp冷却
	FIXMSG_SLOW_MP_COOLTIME,			// 持续回mp冷却
	FIXMSG_SLOW_HPMP_COOLTIME,			// 持续回hp和mp冷却

	FIXMSG_HOTKEY_REG_BYOTHER,			// 445 热键已被其他程序注册
	FIXMSG_NEED_CHOSE_TARGET,			// 请先选中目标
	FIXMSG_RACE_HUMAN,					// 人族
	FIXMSG_RACE_ORC,					// 兽族
	FIXMSG_GAIN_ACHIEVEMENT_POINT,		// 获得成就点
	
	FIXMSG_WEAPON_MISMATCH,				// 450 释放技能武器限制
	FIXMSG_FORBID_MEDICINE,				// 禁掉吃药
	FIXMSG_FORBID_RUNHELPER,			// 禁掉天人合一
	FIXMSG_SHIELD_SKILL,				// 禁掉技能
	FIXMSG_FORBID_MOVE,					// 禁止移动
	
	FISMSG_TRANSPORT_LIMIT,				// 455等级不足，无法传送
	FIXMSG_SKILL_DISABLED,				// 技能不可用
	FIXMSG_ATTACK_DISABLED,				// 当前状态无法进行攻击
	FIXMSG_NPC_OWNER_NAME,				// 从属玩家的名字 
	FIXMSG_SKILL_BATTLE_LIMIT,			// 战场外不可用

	FIXMSG_SKILL_FIGHT_LIMIT,			// 460战斗中不可用
	FIXMSG_SKILL_FIGHT_LIMIT2,			// 非战斗状态下不可用
	FIXMSG_SKILL_CLONE_LIMIT,			// 没有分身状态下不可用
	FIXMSG_SKILL_MOUNT_LIMIT,			// 骑乘状态下不可用
	FIXMSG_SKILL_FLY_LIMIT,				// 飞行状态下不可用
	
	FIXMSG_CIRCLE_AWARD_EXP,			// 465圈子奖励经验
	FIXMSG_RANDOM_LINE,					// 跨服因为线路满而随即分配线路的提示
	FIXMSG_DEITY_LEVELUP,				// 封神后元神升级
	FIXMSG_DP_COOLTIME,					// 瞬回DP药品冷却中
	FIXMSG_SLOW_DP_COOLTIME,			// 持续回DP药品冷却中
	
	FIXMSG_GOT_DEITY_EXP,				// 470获得封神修为
	FIXMSG_CULTIVATION_MISMATCH,		// 无法释放非本阵营技能
	FIXMSG_NEEDDP,						// 元力不足，无法使用该技能
	FIXMSG_GET_BONUS,					// 获得鸿利元宝
	FIXMSG_GEM_UPGRADE_SUCCESS,			// 宝石升品成功

	FIXMSG_GEM_UPGRADE_FAIL,			// 475宝石升品失败
	FIXMSG_GEM_SMELT_FAIL,				// 无法进行宝石熔炼
	FIXMSG_FRIENDCALLBACK_AWARD_EXP,	// 快雪时晴发送邮件奖励经验
	FIXMSG_CIRCLE_OF_DOOM_STARTUP,		// 通知成员开始结阵广播消息
	FIXMSG_PROF_65,						// 职业ID 65

	FIXMSG_PROF_66,						// 480
	FIXMSG_PROF_67,	
	FIXMSG_PROF_68,
	FIXMSG_PROF_69,
	FIXMSG_PROF_70,	

	FIXMSG_PROF_71,						// 485
	FIXMSG_PROF_72,
	FIXMSG_PROF_73,
	FIXMSG_PROF_74,
	FIXMSG_PROF_75,
	
	FIXMSG_PROF_76,						// 490
	FIXMSG_PROF_77,
	FIXMSG_PROF_78,
	FIXMSG_PROF_79,
	FIXMSG_PROF_80,
	
	FIXMSG_PROF_81,						// 495
	FIXMSG_PROF_82,
	FIXMSG_PROF_83,
	FIXMSG_PROF_84,
	FIXMSG_PROF_85,

	FIXMSG_PROF_86,						// 500
	FIXMSG_PROF_87,
	FIXMSG_PROF_88,
	FIXMSG_PROF_89,
	FIXMSG_PROF_90,

	FIXMSG_PROF_91,						// 505
	FIXMSG_PROF_92,
	FIXMSG_PROF_93,
	FIXMSG_PROF_94,
	FIXMSG_PROF_95,

	FIXMSG_PROF_96,						// 510
	FIXMSG_PROF_97,
	FIXMSG_PROF_98,
	FIXMSG_PROF_99,
	FIXMSG_PROF_100,

	FIXMSG_PROF_101,					// 515
	FIXMSG_PROF_102,
	FIXMSG_PROF_103,
	FIXMSG_PROF_104,
	FIXMSG_PROF_105,

	FIXMSG_PROF_106,					// 520
	FIXMSG_PROF_107,
	FIXMSG_PROF_108,
	FIXMSG_PROF_109,
	FIXMSG_PROF_110,

	FIXMSG_PROF_111,					// 525
	FIXMSG_PROF_112,
	FIXMSG_PROF_113,
	FIXMSG_PROF_114,
	FIXMSG_PROF_115,

	FIXMSG_PROF_116,					// 530
	FIXMSG_PROF_117,
	FIXMSG_PROF_118,
	FIXMSG_PROF_119,
	FIXMSG_PROF_120,

	FIXMSG_PROF_121,					// 535
	FIXMSG_PROF_122,
	FIXMSG_PROF_123,
	FIXMSG_PROF_124,
	FIXMSG_PROF_125,

	FIXMSG_PROF_126,					// 540
	FIXMSG_PROF_127,
	FIXMSG_PROF_128,
	FIXMSG_COD_TYPE_TEAM,				// 组队阵法
	FIXMSG_COD_TYPE_FACTION,			// 帮派阵法
	
	FIXMSG_COD_TYPE_FAMILY,				// 545 家族阵法

};

//	Description define
enum
{
	//	Item description ...
	ITEMDESC_ATKSPD_VERYSLOW = 0,		//	0, Attack speed
	ITEMDESC_ATKSPD_SLOW,
	ITEMDESC_ATKSPD_NORMAL,
	ITEMDESC_ATKSPD_FAST,
	ITEMDESC_ATKSPD_VERYFAST,

	ITEMDESC_COL_WHITE,					//  colors
	ITEMDESC_COL_PURPLE,
	ITEMDESC_COL_BLUE,
	ITEMDESC_COL_LIGHTBLUE,
	ITEMDESC_COL_GREEN,

	ITEMDESC_COL_RED,
	ITEMDESC_COL_DARKGOLD,
	ITEMDESC_COL_GRAY,
	ITEMDESC_COL_YELLOW,
	ITEMDESC_COL_CYANINE,

	ITEMDESC_NAMESOCKET,				//	15, name (socket num)
	ITEMDESC_CLASSNAME,					//	Item class name
	ITEMDESC_ATKSPEED,					//	Attack speed
	ITEMDESC_PHYDAMAGE,
	ITEMDESC_MAGICDAMAGE,

	ITEMDESC_ENDURANCE,					//	20
	ITEMDESC_LEVELREQ,
	ITEMDESC_STRENGTHREQ,
	ITEMDESC_AGILITYREQ,
	ITEMDESC_PRICE,

	ITEMDESC_PHYDEFENCE,
	ITEMDESC_GOLDDEFENCE,
	ITEMDESC_WOODDEFENCE,
	ITEMDESC_WATERDEFENCE,
	ITEMDESC_FIREDEFENCE,

	ITEMDESC_EARTHDEFENCE,
	ITEMDESC_NAMENUMBER,				//	name (number)
	ITEMDESC_REMAINTIME,				//	Remained time
	ITEMDESC_NAME,
	ITEMDESC_ADDPHYDAMAGE,

	ITEMDESC_ADDMAGICDAMAGE,
	ITEMDESC_DODGE,
	ITEMDESC_ADDHP,
	ITEMDESC_ADDMP,
	ITEMDESC_NOTDEAL,

	ITEMDESC_WEAPONREQ,					//	40
	ITEMDESC_TASKITEM,
	ITEMDESC_ATKDISTANCE,				//	Attack distance
	ITEMDESC_PHYDEFEXTRA,
	ITEMDESC_RUNSPEEDEXTRA,

	ITEMDESC_DODGEEXTRA,
	ITEMDESC_PHYRESIST,
	ITEMDESC_HPRECOVER,
	ITEMDESC_MPRECOVER,
	ITEMDESC_ATKTIME,

	ITEMDESC_CASTTIME,
	ITEMDESC_DEADLYSTRIKE,
	ITEMDESC_FIREWORKTIME,
	ITEMDESC_PETLEVEL,
	ITEMDESC_ATKRATINGEXTRA,

	ITEMDESC_EXP,
	ITEMDESC_RANDOMPROP,				
	ITEMDESC_PHYDMGEXTRA,
	ITEMDESC_MAGICDMGEXTRA,
	ITEMDESC_CASTSKILL,

	ITEMDESC_MAXPHYDAMAGE,				//  60
	ITEMDESC_MAXMAGICDAMAGE,
	ITEMDESC_ENDURANCEEXTRA,
	ITEMDESC_REQEXTRA,
	ITEMDESC_ALLMAGICDEF,

	ITEMDESC_GOLDDEFEXTRA,
	ITEMDESC_WOODDEFEXTRA,
	ITEMDESC_WATERDEFEXTRA,
	ITEMDESC_FIREDEFEXTRA,
	ITEMDESC_EARTHDEFEXTRA,

	ITEMDESC_HPEXTRA,
	ITEMDESC_MPEXTRA,
	ITEMDESC_ADDATKDIST,
	ITEMDESC_PROJECTILE,
	ITEMDESC_ATKRATING,

	ITEMDESC_2STRINGS,
	ITEMDESC_ADDHPINTIME,	
	ITEMDESC_ADDMPINTIME,	
	ITEMDESC_ADDHPMPINTIME,	
	ITEMDESC_ANTIDOTE,		

	ITEMDESC_ALLMAGICRESIST,			//  80
	ITEMDESC_USEEFFECT,
	ITEMDESC_RECRUITHP,
	ITEMDESC_RECRUITMP,
	ITEMDESC_RECRUITHPMP,

	ITEMDESC_LEVEL,
	ITEMDESC_USEREQUIREMENT,
	ITEMDESC_MAXLEVELREQ,
	ITEMDESC_WEAPONLVLREQ,
	ITEMDESC_ELEMENTTIME,

	ITEMDESC_ADDFLYSPEED,
	ITEMDESC_MPCONSUME,
	ITEMDESC_PROFESSIONREQ,
	ITEMDESC_RUNSPEED,
	ITEMDESC_GENDERREQ,

	ITEMDESC_ERRORITEM,
	ITEMDESC_COLOR,
	ITEMDESC_PENTAGON,
	ITEMDESC_COLORRECT,
	ITEMDESC_UNITPRICE,
	
	ITEMDESC_REPAIRCOST,			//	100	
	ITEMDESC_VALIDTIME,
	ITEMDESC_VITALITYREQ,
	ITEMDESC_ENERGYREQ,
	ITEMDESC_ERRORPROP,
	
	ITEMDESC_STRENGTH,
	ITEMDESC_AGILITY,
	ITEMDESC_VITALITY,
	ITEMDESC_ENERGY,
	ITEMDESC_CASTSKILL2,

	ITEMDESC_ADDFLYSPEED2,
	ITEMDESC_MADEFROM,
	ITEMDESC_WEAKDIST,
	ITEMDESC_FOODTYPE,
	ITEMDESC_FOOD_GRASS,

	ITEMDESC_FOOD_MEAT,
	ITEMDESC_FOOD_VEGETABLE,
	ITEMDESC_FOOD_FRUIT,
	ITEMDESC_FOOD_WATER,
	ITEMDESC_MOVESPEED,

	//	Command description ...
	CMDDESC_SITDOWN,				//	120		
	CMDDESC_WALKRUN,
	CMDDESC_NORMALATTACK,
	CMDDESC_FINDTARGET,
	CMDDESC_ASSISTATTACK,

	CMDDESC_INVITETOTEAM,
	CMDDESC_LEAVETEAM,
	CMDDESC_KICKTEAMMEM,
	CMDDESC_FINDTEAM,
	CMDDESC_STARTTRADE,

	CMDDESC_SELLBOOTH,
	CMDDESC_BUYBOOTH,
	CMDDESC_INVITETOFACTION,
	CMDDESC_FLY,
	CMDDESC_PICKUP,

	CMDDESC_GATHER,	
	CMDDESC_RUSHFLY,
	CMDDESC_BINDBUDDY,
	CMDDESC_SKILLGROUP,
	CMDDESC_NULL3,

	//	Emotion description ...
	FACEDESC_WAVEHAND,				//	140	
	FACEDESC_NOD,
	FACEDESC_SHADEHEAD,
	FACEDESC_SHRUG,
	FACEDESC_LAUGH,

	FACEDESC_ANGRY,	
	FACEDESC_FAINT,
	FACEDESC_SAD,
	FACEDESC_KISSHAND,
	FACEDESC_SHY,	

	FACEDESC_SALUTE,
	FACEDESC_SITDOWN,	
	FACEDESC_CHARGE,	
	FACEDESC_THINK,		
	FACEDESC_CHALLENGE,

	FACEDESC_WIN,
	FACEDESC_GAPE,
	FACEDESC_KISS,
	FACEDESC_FIGHT,
	FACEDESC_ATTACK1,

	FACEDESC_ATTACK2,				//	160	
	FACEDESC_ATTACK3,
	FACEDESC_ATTACK4,
	FACEDESC_DEFENCE,
	FACEDESC_FALL,

	FACEDESC_FALLONGROUND,
	FACEDESC_LOOKAROUND,
	FACEDESC_DANCE,
	FACEDESC_NULL00, 
	FACEDESC_NULL01,

	ITEMDESC_EQUIPADDON_1,
	ITEMDESC_EQUIPADDON_2,
	ITEMDESC_EQUIPADDON_3,
	ITEMDESC_EQUIPADDON_4,
	ITEMDESC_EQUIPADDON_5,

	ITEMDESC_EQUIPADDON_6,
	ITEMDESC_EQUIPADDON_7,
	ITEMDESC_EQUIPADDON_8,
	ITEMDESC_EQUIPADDON_9,
	ITEMDESC_EQUIPADDON_10,

	ITEMDESC_EQUIPADDON_11,				//	180	
	ITEMDESC_EQUIPADDON_12,
	ITEMDESC_EQUIPADDON_13,
	ITEMDESC_EQUIPADDON_14,
	ITEMDESC_EQUIPADDON_15,

	ITEMDESC_EQUIPADDON_16,
	ITEMDESC_EQUIPADDON_17,
	ITEMDESC_EQUIPADDON_18,
	ITEMDESC_EQUIPADDON_19,
	ITEMDESC_EQUIPADDON_20,

	ITEMDESC_EQUIPADDON_21,
	ITEMDESC_EQUIPADDON_22,
	ITEMDESC_EQUIPADDON_23,
	ITEMDESC_EQUIPADDON_24,
	ITEMDESC_EQUIPADDON_25,

	ITEMDESC_EQUIPADDON_26,
	ITEMDESC_EQUIPADDON_27,
	ITEMDESC_EQUIPADDON_28,
	ITEMDESC_EQUIPADDON_29,
	ITEMDESC_EQUIPADDON_30,

	ITEMDESC_EQUIPADDON_31,				//	200	
	ITEMDESC_EQUIPADDON_32,
	ITEMDESC_EQUIPADDON_33,
	ITEMDESC_EQUIPADDON_34,
	ITEMDESC_EQUIPADDON_35,

	ITEMDESC_EQUIPADDON_36,
	ITEMDESC_ENAME,
	ITEMDESC_PNAME,
	ITEMDESC_SNAME,
	ITEMDESC_REFINETICKET1,

	ITEMDESC_REFINETICKET2,
	ITEMDESC_PSTONEADDON_PREFIX,
	ITEMDESC_SSTONEADDON_PREFIX,
	ITEMDESC_ALREADYLEARNED,
	ITEMDESC_LEVELREQ_DROP,

	ITEMDESC_EXPIRETIME_DAY,
	ITEMDESC_EXPIRETIME_HOUR_MIN,
	ITEMDESC_EXPIRETIME_MIN_SEC,
	ITEMDESC_EXPIRETIME_SECOND,
	ITEMDESC_PRODUCE_LEVEL,

	ITEMDESC_PRICEWITHTOTAL,			//	220	
	ITEMDESC_PRICETAG_GOLD,
	ITEMDESC_PRICETAG_SILVER,
	ITEMDESC_PRICETAG_COPPER,
	ITEMDESC_DOUBLEEXP_TIME,

	ITEMDESC_ALL,						//	225
	ITEMDESC_EQUIP_BINDED,
	ITEMDESC_EQUIP_BINDAFTEREQUIP,
	ITEMDESC_DESTROYINGNAME,
	ITEMDESC_EQUIPADDON_37,

	ITEMDESC_FATALERROR,				//	230
	ITEMDESC_DICED,
	ITEMDESC_SUITE_PROP,
	ITEMDESC_EQUIP_BINDAFTERUSE,
	ITEMDESC_SECT_REQUIRE,

	ITEMDESC_LEVEL2_REQUIRE,			//	235
	ITEMDESC_EQUIPADDON_38,
	ITEMDESC_EQUIPSTONE_COLOR1,
	ITEMDESC_EQUIPSTONE_COLOR2,
	ITEMDESC_EQUIPSTONE_COLOR3,

	ITEMDESC_EQUIPSTONE_COLOR4,			//	240
	ITEMDESC_EQUIPSTONE_COLOR5,
	ITEMDESC_EQUIPSTONE_COLOR6,
	ITEMDESC_EQUIPSTONE_COLOR7,
	ITEMDESC_EQUIPSTONE_COLOR8,

	ITEMDESC_EQUIPSTONE_COLOR9,			//	245
	ITEMDESC_EQUIPSTONE_COLOR10,
	ITEMDESC_EQUIPSTONE_COLOR11,
	ITEMDESC_EQUIPSTONE_COLOR12,
	ITEMDESC_EQUIPSTONE_COLOR13,

	ITEMDESC_EQUIPSTONE_COLOR14,		//	250
	ITEMDESC_EQUIPSTONE_COLOR15,
	ITEMDESC_EQUIPSTONE_COLOR16,
	ITEMDESC_EQUIPSTONE_COLOR17,
	ITEMDESC_EQUIPSTONE_COLOR18,

	ITEMDESC_EQUIPSTONE_COLOR19,		//	255
	ITEMDESC_EQUIPSTONE_COLOR20,
	ITEMDESC_TALISMAN_OWNER,
	ITEMDESC_TALISMAN_EXPFOOD,
	ITEMDESC_TALISMAN_LEVEL,

	ITEMDESC_TALISMAN_QUALITY,		    //	260
	ITEMDESC_TALISMAN_MAXENERGY,
	ITEMDESC_TALISMAN_EXP,
	ITEMDESC_TALISMAN_RESIST_1,
	ITEMDESC_TALISMAN_RESIST_2,

	ITEMDESC_TALISMAN_RESIST_3,			//	265	
	ITEMDESC_TALISMAN_RESIST_4,
	ITEMDESC_TALISMAN_RESIST_5,
	ITEMDESC_TALISMAN_RESIST_6,
	ITEMDESC_TALISMAN_QUALITYLEVEL0,

	ITEMDESC_TALISMAN_QUALITYLEVEL1,	//	270
	ITEMDESC_TALISMAN_QUALITYLEVEL2,
	ITEMDESC_TALISMAN_HOUR0,
	ITEMDESC_TALISMAN_HOUR1,
	ITEMDESC_TALISMAN_HOUR2,

	ITEMDESC_TALISMAN_HOUR3,			//	275
	ITEMDESC_TALISMAN_HOUR4,
	ITEMDESC_TALISMAN_HOUR5,
	ITEMDESC_TALISMAN_HOUR6,
	ITEMDESC_TALISMAN_HOUR7,

	ITEMDESC_TALISMAN_HOUR8,			//	280
	ITEMDESC_TALISMAN_HOUR9,
	ITEMDESC_TALISMAN_HOUR10,
	ITEMDESC_TALISMAN_HOUR11,
	ITEMDESC_TALISMAN_MINUTE0,

	ITEMDESC_TALISMAN_MINUTE1,			//	285
	ITEMDESC_TALISMAN_MINUTE2,
	ITEMDESC_TALISMAN_MINUTE3,
	ITEMDESC_TALISMAN_ORG0,
	ITEMDESC_TALISMAN_ORG1,

	ITEMDESC_TALISMAN_ORG2,				//	290
	ITEMDESC_TALISMAN_ORG3,
	ITEMDESC_TALISMAN_ORG4,
	ITEMDESC_TALISMAN_ORG5,
	ITEMDESC_TALISMAN_ENERGYFOOD,

	ITEMDESC_TOWNSCROLL,				//	295
	ITEMDESC_PET_ORG0,
	ITEMDESC_PET_ORG1,
	ITEMDESC_PET_ORG2,
	ITEMDESC_PET_ORG3,

	ITEMDESC_PET_ORG4,					//	300
	ITEMDESC_PET_ORG5,
	ITEMDESC_PET_ORG6,
	ITEMDESC_PET_MAINTYPE0,
	ITEMDESC_PET_MAINTYPE1,

	ITEMDESC_PET_MAINTYPE2,				//	305
	ITEMDESC_PET_MAINTYPE3,
	ITEMDESC_PET_MAINTYPE4,
	ITEMDESC_PET_MAINTYPE5,
	ITEMDESC_PET_MAINTYPE6,

	ITEMDESC_PET_MAINTYPE7,				//	310
	ITEMDESC_PET_MAINTYPE8,
	ITEMDESC_PET_MAINTYPE9,
	ITEMDESC_PET_MAINTYPE10,
	ITEMDESC_PET_MAINTYPE11,

	ITEMDESC_PET_MAINTYPE12,			//	315
	ITEMDESC_316,
	ITEMDESC_317,
	ITEMDESC_318,
	ITEMDESC_319,

	ITEMDESC_320,						//  320
	ITEMDESC_321,
	ITEMDESC_PET_RACE0,
	ITEMDESC_PET_RACE1,
	ITEMDESC_PET_RACE2,

	ITEMDESC_PET_RACE3,					//	325
	ITEMDESC_PET_RACE4,
	ITEMDESC_PET_RACE5,
	ITEMDESC_PET_RACE6,
	ITEMDESC_PET_RACE7,

	ITEMDESC_PET_RACE8,					//	330
	ITEMDESC_PET_RACE9,
	ITEMDESC_PET_RACE10,
	ITEMDESC_PET_RACE11,
	ITEMDESC_PET_RACE12,

	ITEMDESC_PET_RACE13,				//	335
	ITEMDESC_PET_RACE14,
	ITEMDESC_PET_RACE15,
	ITEMDESC_PET_HOROSCOPE0,
	ITEMDESC_PET_HOROSCOPE1,

	ITEMDESC_PET_HOROSCOPE2,			//  340
	ITEMDESC_PET_HOROSCOPE3,
	ITEMDESC_PET_HOROSCOPE4,
	ITEMDESC_PET_HOROSCOPE5,
	ITEMDESC_PET_HOROSCOPE6,

	ITEMDESC_PET_HOROSCOPE7,			//	345
	ITEMDESC_PET_HOROSCOPE8,
	ITEMDESC_PET_RACE,
	ITEMDESC_PET_LEVEL,
	ITEMDESC_PET_ORG,

	ITEMDESC_PET_MASTER,				//	350
	ITEMDESC_PET_MAINTYPE,
	ITEMDESC_PET_TALENT,
	ITEMDESC_PET_STAR,
	ITEMDESC_PET_HP,

	ITEMDESC_PET_VIGOR,					//	355
	ITEMDESC_PET_ATTACK,
	ITEMDESC_PET_DEFENCE,
	ITEMDESC_PET_HIT,
	ITEMDESC_PET_JOUK,

	ITEMDESC_PET_RESISTANCE0,			//	360
	ITEMDESC_PET_RESISTANCE1,
	ITEMDESC_PET_RESISTANCE2,
	ITEMDESC_PET_RESISTANCE3,
	ITEMDESC_PET_RESISTANCE4,

	ITEMDESC_PET_RESISTANCE5,			//	365
	ITEMDESC_PET_LIFE,
	ITEMDESC_PET_HUNGER,
	ITEMDESC_PET_HONOR,
	ITEMDESC_PET_LIVING_SKILL,

	ITEMDESC_PET_SKILL,					//	370
	ITEMDESC_PET_BASIC_HP,
	ITEMDESC_PET_BASIC_VIGOR,
	ITEMDESC_PET_BASIC_ATTACK,
	ITEMDESC_PET_BASIC_DEFENCE,

	ITEMDESC_PET_BASIC_HIT,				//	375
	ITEMDESC_PET_BASIC_JOUK,
	ITEMDESC_PET_UN_IDENTIFY,
	CMDDESC_PET_CALL,
	CMDDESC_PET_COMBINE1,

	CMDDESC_PET_COMBINE2,				//	380
	ITEMDESC_RENASCENCE_REQUIRED,
	ITEMDESC_RENASCENCE_1,
	ITEMDESC_RENASCENCE_2,
	ITEMDESC_RENASCENCE_3,

	ITEMDESC_SECT1_REQUIRE,				//	385
	ITEMDESC_SECT2_REQUIRE,
	ITEMDESC_SECT3_REQUIRE,
	ITEMDESC_PET_RACE_REQUIRE,
	ITEMDESC_PET_ASTRO_REQUIRE,

	ITEMDESC_PET_ASTRO_LEV_REQUIRE,		//	390
	ITEMDESC_PET_EQUIP_LOC,
	ITEMDESC_PET_EQUIP_LOC_1,
	ITEMDESC_PET_EQUIP_LOC_2,
	ITEMDESC_PET_EQUIP_LOC_3,

	ITEMDESC_PET_EQUIP_LOC_4,			//	395
	ITEMDESC_PET_EQUIP_LOC_5,
	ITEMDESC_PET_EQUIP_LOC_6,
	ITEMDESC_PET_EQUIP_LOC_7,
	ITEMDESC_PET_EQUIP_LOC_8,

	ITEMDESC_PET_EQUIP_LOC_9,			//	400
	ITEMDESC_PET_EQUIP_LOC_10,
	ITEMDESC_PET_EQUIP_LOC_11,
	ITEMDESC_PET_EQUIP_LOC_12,
	ITEMDESC_PET_ADOPT,

	ITEMDESC_PET_UN_ADOPT,				//	405
	ITEMDESC_PET_AUTOFOOD_VALUE,
	ITEMDESC_PET_AUTOFOOD_GEN1,
	ITEMDESC_PET_AUTOFOOD_GEN2,
	ITEMDESC_PET_AUTOFOOD_GEN3,
	
	ITEMDESC_PET_ELEMENT0,				//	410
	ITEMDESC_PET_ELEMENT1,
	ITEMDESC_PET_ELEMENT2,
	ITEMDESC_PET_ELEMENT3,
	ITEMDESC_PET_ELEMENT4,

	ITEMDESC_PET_ELEMENT5,				//	415
	ITEMDESC_PET_ELEMENT6,
	ITEMDESC_PET_ELEMENT7,
	ITEMDESC_PET_ELEMENT8,
	ITEMDESC_PET_ELEMENT9,

	ITEMDESC_PET_ELEMENT10,				//	420
	ITEMDESC_PET_ELEMENT11,
	ITEMDESC_PET_ELEMENT12,
	ITEMDESC_PET_ELEMENT13,
	ITEMDESC_PET_ELEMENT14,

	ITEMDESC_PET_ELEMENT15,				//	425
	ITEMDESC_PET_ELEMENT16,
	ITEMDESC_PET_ELEMENT17,
	ITEMDESC_PET_HOROSCOPE,
	ITEMDESC_FLYSWORD_OWNER,

	ITEMDESC_FLYSWORD_STAR,				//	430
	ITEMDESC_FLYSWORD_STAR1,
	ITEMDESC_FLYSWORD_STAR2,
	ITEMDESC_FLYSWORD_STAR3,
	ITEMDESC_FLYSWORD_STAR4,

	ITEMDESC_FLYSWORD_EXP,				//	435
	ITEMDESC_FLY_SPEED,
	ITEMDESC_EQUIPADDON_40,
	ITEMDESC_FLYSWORD_QUALITY0,
	ITEMDESC_FLYSWORD_QUALITY1,

	ITEMDESC_FLYSWORD_QUALITY2,			//	440
	ITEMDESC_FLYSWORD_QUALITY3,
	ITEMDESC_FLYSWORD_QUALITY4,
	ITEMDESC_FLYSWORD_QUALITY5,
	ITEMDESC_FLYSWORD_QUALITY6,

	ITEMDESC_FLYSWORD_QUALITY7,			//	445
	ITEMDESC_FLYSWORD_QUALITY8,
	ITEMDESC_FLYSWORD_QUALITY,
	ITEMDESC_RECIPE_CLASS1,
	ITEMDESC_RECIPE_CLASS2,

	ITEMDESC_RECIPE_TECH,				//	450
	ITEMDESC_RECIPE_CONSTRUCTION,
	ITEMDESC_RECIPE_PRODUCT,
	ITEMDESC_RECIPE_MATERIAL,
	ITEMDESC_EQUIPADDON_41,

	ITEMDESC_EQUIPADDON_42,				//	455
	ITEMDESC_EQUIPADDON_43,
	ITEMDESC_EQUIPADDON_44,
	ITEMDESC_EQUIPADDON_45,
	ITEMDESC_EQUIPADDON_46,

	ITEMDESC_CANT_TRADE,				//	460
	ITEMDESC_CANT_SELL,
	ITEMDESC_GOD_DEVIL_REQUIRE,
	ITEMDESC_GOD_DEVIL_SUFFIX2,
	ITEMDESC_GOD_DEVIL_SUFFIX3,

	ITEMDESC_GOD_DEVIL_SUFFIX4,			//	465
	ITEMDESC_GOD_DEVIL_SUFFIX5,
	ITEMDESC_GOD_DEVIL_SUFFIX6,
	ITEMDESC_TITLE_REQUIRE,
	ITEMDESC_EQUIPADDON_47,

	ITEMDESC_EQUIPADDON_48,				//	470
	ITEMDESC_EQUIPADDON_49,
	ITEMDESC_EQUIPADDON_50,
	ITEMDESC_EQUIPADDON_51,
	ITEMDESC_EQUIPADDON_52,

	ITEMDESC_EQUIPADDON_53,				//	475
	ITEMDESC_EQUIPADDON_54,
	ITEMDESC_PET_SKILL_LEVEL,
	ITEMDESC_NEW_DICED,
	ITEMDESC_LOCKED,

	ITEMDESC_EQUIP_REPU_REQUIRE,		//	480
	ITEMDESC_EQUIP_REPU1,
	ITEMDESC_EQUIP_REPU2,
	ITEMDESC_EQUIP_REPU3,
	ITEMDESC_EQUIP_REPU4,

	ITEMDESC_EQUIP_REPU5,				//	485
	ITEMDESC_EQUIP_REPU6,
	ITEMDESC_EQUIP_REPU7,
	ITEMDESC_EQUIP_REPU8,
	ITEMDESC_EQUIP_REPU9,

	ITEMDESC_EQUIP_REPU10,				//	490
	ITEMDESC_EQUIP_REPU11,
	ITEMDESC_EQUIP_REPU12,
	ITEMDESC_EQUIP_REPU13,
	ITEMDESC_EQUIP_REPU14,

	ITEMDESC_EQUIP_REPU15,				//	495
	ITEMDESC_EQUIP_REPU16,
	ITEMDESC_EQUIP_REPU17,
	ITEMDESC_EQUIP_REPU18,
	ITEMDESC_EQUIP_REPU19,

	ITEMDESC_EQUIP_REPU20,				//  500
	ITEMDESC_EQUIP_REPU21,
	ITEMDESC_EQUIP_REPU22,
	ITEMDESC_EQUIP_REPU23,
	ITEMDESC_EQUIP_REPU24,

	ITEMDESC_EQUIP_REPU25,				//  505
	ITEMDESC_EQUIP_REPU26,
	ITEMDESC_UNLOCKING_ITEM,
	ITEMDESC_NO_DROP_WHEN_DIE,
	ITEMDESC_NOT_SELLABLE,

	ITEMDESC_DAMAGED_ITEM,				//	510
	ITEMDESC_EQUIP_SOUL_EFFECT,
	ITEMDESC_EQUIP_SOUL_COST,
	ITEMDESC_EQUIP_SOUL_FACTION_LIMIT,
	ITEMDESC_EQUIP_SOUL_LEVEL_LIMIT,
	
	ITEMDESC_EQUIP_SOUL_LOCATION_LIMIT,	//	515
	ITEMDESC_EQUIP_SOUL_HOLE_LIMIT,
	ITEMDESC_GOLD,
	ITEMDESC_WOOD,
	ITEMDESC_WATER,
	
	ITEMDESC_FIRE,						//	520
	ITEMDESC_EARTH,
	ITEMDESC_WEAPON,            
	ITEMDESC_HAT,
	ITEMDESC_CLOTHES,

	ITEMDESC_SHOE,						//	525
	ITEMDESC_EQUIP_HOST,			// 装备主人
	ITEMDESC_SOUL_VALUE,			// 魂 %d/%d
	ITEMDESC_BLOOD_SACRIFICE,		// (血祭)
	ITEMDESC_SOUL_LEVEL,            // 灵力等级
	
	ITEMDESC_EQUIP_SOUL,			// 器魄·	530
	ITEMDESC_ACTIVATE_SOUL_SUITE,	// 激活
	ITEMDESC_EQUIP_SOUL2,			// 器魄(%s)·
	ITEMDESC_PET_ARMOR,             // 宠物装备
	ITEMDESC_LOTTERY,				// 彩票
	
	ITEMDESC_UNDRAW_LOTTERY,		// 535 未抽奖
	ITEMDESC_ANGLE_BRACKET,			// 尖括号
	ITEMDESC_GIFT_BAG,				// 礼包
	ITEMDESC_MALE,					// 男生
	ITEMDESC_FEMALE,				// 女生

	// 540
	ITEMDESC_GIFT_BAG_NEED_ITEM,	// 540 开启需要道具	
	ITEMDESC_GIFT_BAG_NEED_MONEY,	// 开启需要金钱
	ITEMDESC_GIFT_BAG_NEED_SPACE,	// 开启礼包需要包裹空间
	ITEMDESC_ADD_NUM,				// + %d
	ITEMDESC_HP,					// 气血

	// 545
	ITEMDESC_MP,					// 真气
	ITEMDESC_COL_EARTHYELLOW,		// 土黄色
	ITEMDESC_COL_POOLBLUE,			// 浅蓝色
	ITEMDESC_COL_RESERVE3,
	ITEMDESC_COL_RESERVE4,

	// 550
	ITEMDESC_COL_RESERVE5,
	ITEMDESC_COL_RESERVE6,
	ITEMDESC_COL_RESERVE7,
	ITEMDESC_COL_RESERVE8,
	ITEMDESC_COL_RESERVE9,
	
	// 555
	ITEMDESC_STRCAT,				// %s的%s
	ITEMDESC_LEVELUPPERLIMIT,		// 等级上限要求
	ITEMDESC_RACEREQ,				// 种族限制
	ITEMDESC_CARD_OWENER,			// 灵魂契约者：%s
	ITEMDESC_WAKAN,					// 灵力：%d

	// 560
	ITEMDESC_WAKAN_CONSISTENT,		// 灵力契合度：x阶（x%）
	ITEMDESC_CARD_GRADE,			// 幻化石品级
	ITEMDESC_CARD_GRADE1,			// 正品
	ITEMDESC_CARD_GRADE2,			// 良品
	ITEMDESC_CARD_GRADE3,			// 优秀

	// 565
	ITEMDESC_CARD_GRADE4,			// 杰出
	ITEMDESC_CARD_GRADE5,			// 变异
	ITEMDESC_CARD_LEVEL,			// 幻化石等级
	ITEMDESC_MONSTER_FACTION1,		// 怪物阵营详细划分
	ITEMDESC_MONSTER_FACTION2,
	
	// 570
	ITEMDESC_MONSTER_FACTION3,
	ITEMDESC_MONSTER_FACTION4,
	ITEMDESC_MONSTER_FACTION5,
	ITEMDESC_MONSTER_FACTION6,
	ITEMDESC_MONSTER_FACTION7,

	// 575
	ITEMDESC_MONSTER_FACTION8,
	ITEMDESC_MONSTER_FACTION9,
	ITEMDESC_MONSTER_FACTION10,
	ITEMDESC_MONSTER_FACTION11,	
	ITEMDESC_MONSTER_FACTION12,

	// 580
	ITEMDESC_MONSTER_FACTION13,
	ITEMDESC_MONSTER_FACTION14,
	ITEMDESC_MONSTER_FACTION15,
	ITEMDESC_MONSTER_FACTION16,
	ITEMDESC_MONSTER_FACTION,		// 种类：%s

	// 585
	ITEMDESC_NO_BOND,				// 尚未契约
	ITEMDESC_WAKAN_CONSISTENT2,		// 灵力契合度: x阶
	ITEMDESC_GARDEN_CROP_USUAL,
	ITEMDESC_GARDEN_CROP_FINE,
	ITEMDESC_GARDEN_CROP_FRUITNUM,

	// 590
	ITEMDESC_GARDEN_CROP_GROWPERIODHOUR,
	ITEMDESC_GARDEN_CROP_GROWPERIODDAY,
	ITEMDESC_GARDEN_CROP_PROTECTPERIODHOUR,
	ITEMDESC_GARDEN_CROP_PROTECTPERIODMIN,
	ITEMDESC_GARDEN_CROP_STEALLIMIT,
	
	// 595
	ITEMDESC_GARDEN_TOOL_CHARMREQ,
	ITEMDESC_GARDEN_TOOL_MONEYREQ,
	ITEMDESC_EVER_LEVELREQ,			// 曾经等级限制
	ITEMDESC_HIDDEN_ADDON,			// 神秘隐藏属性
	ITEMDESC_MERCENARY_CREDENTIAL_FACTION,		// 佣兵凭证所属帮派

	// 600
	ITEMDESC_MERCENARY_CREDENTIAL_TERRITORY,	// 佣兵凭证所属区域
	ITEMDESC_TERRITORY_REQ,			// 社稷需求
	ITEMDESC_TERRITORY_REQ1,
	ITEMDESC_TERRITORY_REQ2,
	ITEMDESC_TERRITORY_REQ3,

	// 605
	ITEMDESC_TERRITORY_REQ4,
	ITEMDESC_TERRITORY_REQ5,
	ITEMDESC_TERRITORY_REQ6,
	ITEMDESC_TERRITORY_REQ7,
	ITEMDESC_TERRITORY_REQ8,

	// 610
	ITEMDESC_TERRITORY_REQ9,
	ITEMDESC_TERRITORY_REQ10,
	ITEMDESC_TERRITORY_REQ11,
	ITEMDESC_TERRITORY_REQ12,
	ITEMDESC_TERRITORY_REQ13,
	
	// 615
	ITEMDESC_TERRITORY_REQ14,
	ITEMDESC_RESERVE01,
	ITEMDESC_RESERVE02,
	ITEMDESC_RESERVE03,
	ITEMDESC_RESERVE04,
	
	// 620
	ITEMDESC_VALIDTIME_DAY,			// 能量剩余：星盘剩余有效时间
	ITEMDESC_VALIDTIME_HOUR_MIN,
	ITEMDESC_VALIDTIME_MIN_SEC,
	ITEMDESC_VALIDTIME_SECOND,
	ITEMDESC_VALIDTIME_ZERO,
	
	// 625
	ITEMDESC_VALIDTIME_DAY2,		// 充能天数
	ITEMDESC_RECRUITDP,				// 瞬回dp
	ITEMDESC_ADDDPINTIME,			// 持续回dp
	ITEMDESC_EQUIPADDON_55,
	ITEMDESC_EQUIPADDON_56,

	// 630
	ITEMDESC_EQUIPADDON_57,
	ITEMDESC_EQUIPADDON_58,
	ITEMDESC_EQUIPADDON_59,
	ITEMDESC_EQUIPADDON_60,
	ITEMDESC_COOLTIME,				// 冷却时间

	//635
	ITEMDESC_GEM_GRADE,				//宝石品级
	ITEMDESC_GEM_SEAL_SHAPE,		//宝石魔印形状属性
	ITEMDESC_GEM_SLOT_SHAPE1,		//宝石插槽形状1 万能插槽
	ITEMDESC_GEM_SLOT_SHAPE2,		//宝石插槽形状2
	ITEMDESC_GEM_SLOT_SHAPE3,		//宝石插槽形状3

	//640
	ITEMDESC_GEM_SLOT_SHAPE4,		//宝石插槽形状4
	ITEMDESC_GEM_SLOT_SHAPE5,		//宝石插槽形状5
	ITEMDESC_GEM_SLOT_SHAPE6,		//宝石插槽形状6
	ITEMDESC_GEM_SLOT_SHAPE7,		//宝石插槽形状7
	ITEMDESC_GEM_SLOT_SHAPE8,		//宝石插槽形状8

	//645
	ITEMDESC_GEM_SLOT_SHAPE9,		//宝石插槽形状9
	ITEMDESC_GEM_SLOT_SHAPE10,		//宝石插槽形状10
	ITEMDESC_GEM_SLOT_SHAPE11,		//宝石插槽形状11
	ITEMDESC_GEM_SLOT_SHAPE12,		//宝石插槽形状12
	ITEMDESC_GEM_SLOT_SHAPE13,		//宝石插槽形状13

	//650
	ITEMDESC_NO_GEM_EMBEDED,		//没有镶嵌宝石
	ITEMDESC_SLOT_AWARD,			//插槽奖励
	ITEMDESC_SLOT_TYPE,				//插槽形状
	ITEMDESC_SLOT_RESERVE1,			//空白
	ITEMDESC_NUMBER_ZERO,			//零
	
	//655
	ITEMDESC_NUMBER_ONE,			//一
	ITEMDESC_NUMBER_TWO,			//二
	ITEMDESC_NUMBER_THREE,			//三
	ITEMDESC_NUMBER_FOUR,			//四
	ITEMDESC_NUMBER_FIVE,			//五
	
	//660
	ITEMDESC_NUMBER_SIX,			//六
	ITEMDESC_NUMBER_SEVEN,			//七
	ITEMDESC_NUMBER_EIGHT,			//八
	ITEMDESC_NUMBER_NINE,			//九
	ITEMDESC_NUMBER_TEN,			//十
	
	//665
	ITEMDESC_RESERVE11,				//RESERVE
	ITEMDESC_RESERVE12,				//RESERVE
	ITEMDESC_RESERVE13,				//RESERVE
	ITEMDESC_RESERVE14,				//RESERVE
	ITEMDESC_RESERVE15,				//RESERVE
	
	//670
	ITEMDESC_RESERVE16,				//RESERVE
	ITEMDESC_RESERVE17,				//RESERVE
	ITEMDESC_RESERVE18,				//RESERVE
	ITEMDESC_RESERVE19,				//RESERVE
	ITEMDESC_RESERVE20,				//RESERVE

	//675
	ITEMDESC_ITEM_BINDAFTERUSE,		//使用后绑定
	ITEMDESC_TALISMAN_TREND0,		//
	ITEMDESC_TALISMAN_TREND1,		//
	ITEMDESC_TALISMAN_TREND2,		//
	ITEMDESC_TALISMAN_TREND3,		//

	//680
	ITEMDESC_TALISMAN_TREND4,		//
	ITEMDESC_TALISMAN_TREND5,		//
	ITEMDESC_TALISMAN_TREND6,		//
	ITEMDESC_TALISMAN_TREND7,		//
	ITEMDESC_TALISMAN_TREND8,		//

	//685
	ITEMDESC_TALISMAN_TREND9,		//
	ITEMDESC_TALISMAN_TREND10,		//
	ITEMDESC_TALISMAN_TREND11,		//
	ITEMDESC_TALISMAN_TREND12,		//
	ITEMDESC_TALISMAN_TREND13,		//

	//690
	ITEMDESC_TALISMAN_TREND14,		//
	ITEMDESC_TALISMAN_TREND15,		//
	ITEMDESC_TALISMAN_TREND16,		//
	ITEMDESC_TALISMAN_TREND17,		//
	ITEMDESC_TALISMAN_TREND18,		//

	//695
	ITEMDESC_TALISMAN_TREND19,		//
	ITEMDESC_TALISMAN_TREND,		//
	ITEMDESC_DPEXTRA,				//	装备的神力属性 Added 2011-08-05.
	ITEMDESC_DEITY_POWER,			//	装备的神圣力属性 Added 2011-08-05.
	ITEMDESC_EQUIPADDON_61,			//	装备附加属性61：附加永久技能 Added 2012-02-20.

	//700
	ITEMDESC_RUNEPROPERTY1,			// 元魂属性开始
/*	---约定好相关参数的id号
	---1：气血
	---2：真气
	---3：攻击
	---4：防御
	---5：命中
	---6：躲闪
	---7：技能命中 (千分数)
	---8：技能躲闪  (千分数)
	---9：元力值
	---10：致命一击率   (千分数)
	---11：致命一击伤害 (float)
	---12：减免致命一击率  (千分数)
	---13：减免致命一击伤害 (float)
	---14：御仙
	---15：御魔
	---16：御佛
	---17：克仙
	---18：克魔
	---19：克佛
	---20：减免固定伤害
	---21：减免伤害百分比
	---22：眩晕抗性
	---23：定身抗性
	---24：魅惑抗性
	---25：虚弱抗性
	---26：昏睡抗性
	---27：减速抗性
	---28：无视伤害减免  
	---29：气血增加百分比
	---30：真气增加百分比
	---31：攻击增加百分比
	---32：防御增加百分比
	---33：元神威能
*/
	ITEMDESC_RUNEPROPERTY41 = 740,			// 元魂属性结束
	ITEMDESC_RUNEQUALITY1,
	ITEMDESC_RUNEQUALITY2,
	ITEMDESC_RUNEQUALITY3,
	ITEMDESC_RUNEQUALITY4,

	// 745
	ITEMDESC_RUNEQUALITY5,
	ITEMDESC_RUNEQUALITY6,
	ITEMDESC_RUNEQUALITY7,
	ITEMDESC_RUNELEVELREQ,
	ITEMDESC_RUNESLOTEMPTY,
	
	// 750
	ITEMDESC_RUNECOLOR1,
	ITEMDESC_RUNECOLOR2,
	ITEMDESC_RUNECOLOR3,
	ITEMDESC_RUNECOLOR4,
	ITEMDESC_RUNECOLOR5,

	// 755
	ITEMDESC_RUNECOLOR6,
	ITEMDESC_RUNECOLOR7,
	ITEMDESC_RUNENAME,
	ITEMDESC_RUNENAME1,
	ITEMDESC_RUNENAME2,

	// 760
	ITEMDESC_RUNENAME3,
	ITEMDESC_RUNENAME4,
	ITEMDESC_RUNENAME5,
	ITEMDESC_RUNENAME6,
	ITEMDESC_RUNENAME7,

	// 765
	ITEMDESC_RUNE_SUITE_PROP,
	ITEMDESC_RUNEDESC1,
	ITEMDESC_RUNEDESC2,
	ITEMDESC_RUNEDESC3,
	ITEMDESC_RUNEDESC4,

	// 770
	ITEMDESC_RUNEDESC5,
	ITEMDESC_RUNEDESC6,
	ITEMDESC_RUNEDESC7,
	ITEMDESC_RUNEDESCORIG,
	ITEMDESC_RUNEDESCHINT,

	// 775
	ITEMDESC_RUNEXP,
	ITEMDESC_RUNEUNOPEN,

};

///////////////////////////////////////////////////////////////////////////
//	
//	Types and Global variables
//	
///////////////////////////////////////////////////////////////////////////


///////////////////////////////////////////////////////////////////////////
//	
//	Declare of Global functions
//	
///////////////////////////////////////////////////////////////////////////


///////////////////////////////////////////////////////////////////////////
//	
//	Inline functions
//	
///////////////////////////////////////////////////////////////////////////

